# Generated by Django 4.2.4 on 2024-01-30 19:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo_estrategico', models.CharField(max_length=255, verbose_name='Nome do Objetivo')),
                ('eixo_estrategico_cd', models.CharField(max_length=10, unique=True, verbose_name='Código do Objetivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.ano', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivo Estratégico',
            },
        ),
        migrations.CreateModel(
            name='Fontes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_cd', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código da Fonte')),
                ('fonte_nm', models.CharField(max_length=255, verbose_name='Nome da Fonte')),
            ],
            options={
                'verbose_name_plural': 'Fontes',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=255, verbose_name='Nome do Programa')),
                ('programa_cd', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código do Programa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.ano', verbose_name='Ano')),
                ('eixo_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.eixo', verbose_name='Nome do Eixo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.tipoprograma', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Programa',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrograma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('programa', models.CharField(max_length=255, verbose_name='Nome do Programa')),
                ('programa_cd', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código do Programa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ano', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.ano', verbose_name='Ano')),
                ('eixo_estrategico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.eixo', verbose_name='Nome do Eixo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.tipoprograma', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical programa',
                'verbose_name_plural': 'historical Programa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFontes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fonte_cd', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código da Fonte')),
                ('fonte_nm', models.CharField(max_length=255, verbose_name='Nome da Fonte')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fontes',
                'verbose_name_plural': 'historical Fontes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEixo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('eixo_estrategico', models.CharField(max_length=255, verbose_name='Nome do Objetivo')),
                ('eixo_estrategico_cd', models.CharField(db_index=True, max_length=10, verbose_name='Código do Objetivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ano', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.ano', verbose_name='Ano')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Objetivo',
                'verbose_name_plural': 'historical Objetivo Estratégico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAcao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Ação')),
                ('acao_cd', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código da Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ano', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.ano', verbose_name='Ano')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orcamento.programa', verbose_name='Nome do Programa')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.tipoacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical acao',
                'verbose_name_plural': 'historical Ação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, unique=True, verbose_name='Nome da Ação')),
                ('acao_cd', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Código da Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.ano', verbose_name='Ano')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.programa', verbose_name='Nome do Programa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.tipoacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Ação',
            },
        ),
    ]
