# Generated by Django 4.2.4 on 2024-01-31 14:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgaos', '0001_initial'),
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.CharField(max_length=255, verbose_name='Política')),
                ('numero', models.IntegerField(verbose_name='Número da reunião')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_termino', models.TimeField(verbose_name='Hora término')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('participante', models.ManyToManyField(to='orgaos.responsavel', verbose_name='Participante')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.secretaria', verbose_name='Nome da secretaria')),
            ],
            options={
                'verbose_name_plural': 'Reuniões',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReuniao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('politica', models.CharField(max_length=255, verbose_name='Política')),
                ('numero', models.IntegerField(verbose_name='Número da reunião')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_termino', models.TimeField(verbose_name='Hora término')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.secretaria', verbose_name='Nome da secretaria')),
            ],
            options={
                'verbose_name': 'historical reuniao',
                'verbose_name_plural': 'historical Reuniões',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEncaminhamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('encaminhamento', models.TextField(verbose_name='Encaminhamento')),
                ('prazo', models.DateField(default=datetime.date.today, verbose_name='Prazo')),
                ('devolutiva', models.TextField(verbose_name='Devolutiva')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gestor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nome do(a) Gestor(a)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reuniao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reunioes.reuniao', verbose_name='Reunião')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'historical encaminhamento',
                'verbose_name_plural': 'historical Encaminhamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('encaminhamento', models.TextField(verbose_name='Encaminhamento')),
                ('prazo', models.DateField(default=datetime.date.today, verbose_name='Prazo')),
                ('devolutiva', models.TextField(verbose_name='Devolutiva')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do(a) Gestor(a)')),
                ('responsavel', models.ManyToManyField(to='orgaos.responsavel', verbose_name='Responsável')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunioes.reuniao', verbose_name='Reunião')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.status', verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Encaminhamentos',
            },
        ),
    ]
