# Generated by Django 4.2.4 on 2024-02-02 19:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgaos', '0001_initial'),
        ('apoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Plano')),
                ('mes', models.CharField(choices=[('1', 'Jan'), ('2', 'Fev'), ('3', 'Mar'), ('4', 'Abr'), ('5', 'Mai'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Ago'), ('9', 'Set'), ('10', 'Out'), ('11', 'Nov'), ('12', 'Dez')], max_length=255, verbose_name='Mês')),
                ('ais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.ais', verbose_name='Nome da AIS')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.ano', verbose_name='Ano')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do(a) Gestor(a)')),
                ('operativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.orgao', verbose_name='Nome da Operativa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.responsavel', verbose_name='Nome do(a) Responsável')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.unidade', verbose_name='Nome da Unidade')),
            ],
            options={
                'verbose_name_plural': 'Plano',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlano',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Plano')),
                ('mes', models.CharField(choices=[('1', 'Jan'), ('2', 'Fev'), ('3', 'Mar'), ('4', 'Abr'), ('5', 'Mai'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Ago'), ('9', 'Set'), ('10', 'Out'), ('11', 'Nov'), ('12', 'Dez')], max_length=255, verbose_name='Mês')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ais', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.ais', verbose_name='Nome da AIS')),
                ('ano', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.ano', verbose_name='Ano')),
                ('gestor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nome do(a) Gestor(a)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operativa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.orgao', verbose_name='Nome da Operativa')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.responsavel', verbose_name='Nome do(a) Responsável')),
                ('unidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.unidade', verbose_name='Nome da Unidade')),
            ],
            options={
                'verbose_name': 'historical plano',
                'verbose_name_plural': 'historical Plano',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAcaoPlano',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Ação')),
                ('diagnostico', models.TextField(blank=True, default='-', null=True, verbose_name='Diagnóstico')),
                ('prioritario', models.BooleanField(default=False, verbose_name='Território Prioritário?')),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('policiais', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Policiais')),
                ('diarias', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Diárias')),
                ('pjes', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='PJES')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('eixo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.eixoplano', verbose_name='Eixo do Plano')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apoio.indicador', verbose_name='Indicador')),
                ('plano', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planos.plano', verbose_name='Plano')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orgaos.responsavel', verbose_name='Nome do(a) Responsável')),
            ],
            options={
                'verbose_name': 'historical acao plano',
                'verbose_name_plural': 'historical Ação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AcaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Ação')),
                ('diagnostico', models.TextField(blank=True, default='-', null=True, verbose_name='Diagnóstico')),
                ('prioritario', models.BooleanField(default=False, verbose_name='Território Prioritário?')),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('policiais', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Policiais')),
                ('diarias', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Diárias')),
                ('pjes', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='PJES')),
                ('bairro', models.ManyToManyField(to='apoio.bairro', verbose_name='Nome do Bairro')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.eixoplano', verbose_name='Eixo do Plano')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoio.indicador', verbose_name='Indicador')),
                ('municipio', models.ManyToManyField(to='apoio.municipio', verbose_name='Nome do Município')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.plano', verbose_name='Plano')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgaos.responsavel', verbose_name='Nome do(a) Responsável')),
                ('turno', models.ManyToManyField(to='apoio.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name_plural': 'Ação',
            },
        ),
    ]
