# Generated by Django 4.2.4 on 2024-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoio', '0002_municipio_turno_bairro'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoplano',
            name='bairro',
            field=models.ManyToManyField(to='apoio.bairro', verbose_name='Nome do Município'),
        ),
        migrations.AddField(
            model_name='acaoplano',
            name='municipio',
            field=models.ManyToManyField(to='apoio.municipio', verbose_name='Nome do Município'),
        ),
        migrations.AddField(
            model_name='acaoplano',
            name='turno',
            field=models.ManyToManyField(to='apoio.turno', verbose_name='Turno'),
        ),
    ]
