# Generated by Django 4.2.4 on 2024-01-30 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoplano',
            name='diarias',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Diárias'),
        ),
        migrations.AlterField(
            model_name='acaoplano',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Ação'),
        ),
        migrations.AlterField(
            model_name='acaoplano',
            name='pjes',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='PJES'),
        ),
        migrations.AlterField(
            model_name='historicalacaoplano',
            name='diarias',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Diárias'),
        ),
        migrations.AlterField(
            model_name='historicalacaoplano',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Ação'),
        ),
        migrations.AlterField(
            model_name='historicalacaoplano',
            name='pjes',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='PJES'),
        ),
    ]
